### ISSUE TITLE
how can i show body only if assert failed?

### ISSUE THREAD

**Issue by fess932** [Orange-OpenSource/hurl#1047]
GET {{BASE_URL}}/user
HTTP/* *
[Asserts]
status == 200

got
```
status == 200
   |   actual:   int <500>
   |   expected: int <200>
```
want
```
status == 200
   |   actual:   int <500>
   |   expected: int <200>
   
   {"error": "server error etc.."}
```

**Comment by jcamiel** [comment]
Hi, 
Currently we don't display the response body if there is an assert error, we could add an option to do this.
As a workaround, you can use [`--very-verbose`](https://hurl.dev/docs/manual.html#very-verbose) option to display the request and response body regardless of the asserts.

**Comment by fabricereix** [comment]
You could write an additional assert for the error field
```
jsonpath "$.error" not exist
```

If you have an error field in your response, it will emit an assert error
```
   | jsonpath "$.error" not exists
   |   actual:   string <server error etc..>
   |   expected: not something
```

**Comment by fess932** [comment]
> You could write an additional assert for the error field
> 
> ```
> jsonpath "$.error" not exist
> ```
> 
> If you have an error field in your response, it will emit an assert error
> 
> ```
>    | jsonpath "$.error" not exists
>    |   actual:   string <server error etc..>
>    |   expected: not something
> ```

Tnx, good workaround!

**Comment by mxa0079** [comment]
Is this closed because of the workaround?

What is the rationale behind swallowing the body when the http assert fails?

**Comment by mxa0079** [comment]
I just tested this and it seems like it is not working:

Test:

![image](https://github.com/Orange-OpenSource/hurl/assets/432881/42bb1a22-6c12-44f3-9ed1-77697ba4f7ea)


Response:


![image](https://github.com/Orange-OpenSource/hurl/assets/432881/5a541431-be07-4ffa-b507-7b7c1a2eaa89)

(it seems that since the status code assert fails, the other ones are skipped)

**Comment by jcamiel** [comment]
Hi @mxa0079 ,

If the status code is not correct, we don't perform any assert. This has been proposed in #1072 and the rationale is that if the status code is not correct, there is a good chance that the received body is completely different than the expected one (for instance you receive a 302 for redirection, or a 4xx for an API error). All the explicit asserts will probably be in error, adding unnecessary clutter.

That said, instead of `--very-verbose` option, you should use [`--error-format long`](https://hurl.dev/docs/manual.html#error-format) that has been added for this exact use case (show body in error):

```shell
$ hurl --test --error-format long *.hurl
```

Could you give it a try and tell us if it's better?

Thanks,

**Comment by mxa0079** [comment]
This is exactly what we ned. Thanks @jcamiel for the prompt response and for all the effort. Hurl is a fantastic tool, I wish you and the rest of the team much success.
