### ISSUE TITLE
--continue-on-error does not work

### ISSUE THREAD

**Issue by kidbrax** [Orange-OpenSource/hurl#2113]
### What is the current *bug* behavior?

Using `--continue-on-error` causes an unexpected argument error	

### Steps to reproduce

Run a hurl test using `--continue-on-error`

```
$ hurl \
  --insecure \
  --variables-file hurl/vars.env \
  --continue-on-error \
  --very-verbose hurl/somefile.hurl
error: error: unexpected argument '--continue-on-error' found

  tip: a similar argument exists: '--connect-to'

Usage: hurl --insecure --variables-file <FILE> --connect-to <HOST1:PORT1:HOST2:PORT2> [input_files]...

For more information, try '--help'.
```

### What is the expected *correct* behavior?

The tests should continue after an error occurs

### Execution context

- Hurl Version (`hurl --version`):
```
$ hurl --version
hurl 4.0.0 libcurl/8.1.2 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.12 nghttp2/1.55.1
Features (libcurl):  alt-svc AsynchDNS HSTS HTTP2 IPv6 Largefile libz NTLM NTLM_WB SPNEGO SSL UnixSockets
Features (built-in): brotli
```

- Operating system and version:
```
$ sw_vers
ProductName: 	macOS
ProductVersion:	14.1
BuildVersion:		23B74
```

### Possible fixes

n/a

**Comment by jcamiel** [comment]
Hi @kidbrax 
[`--continue-on-error`](https://hurl.dev/docs/manual.html#continue-on-error) has been introduced in [Hurl 4.1.0](https://github.com/Orange-OpenSource/hurl/releases/tag/4.1.0)
Prior this version, the option was named `--fail-at-end` (we changed it because we find it to be clearer). You should either upgrade to Hurl 4.1.0 or use `--fail-at-end`.

**Comment by kidbrax** [comment]
Ah, got it. Thanks for the quick response.
