### ISSUE TITLE
Asynchronous API calls

### ISSUE THREAD

**Issue by janwytze** [Orange-OpenSource/hurl#2274]
### Problem to solve

I have an API endpoint that runs a task (`/run-task`), and an API endpoint that marks the task as completed (`/complete-task/:id`). The API endpoint that is used to run the task only completes when the API endpoint that marks the task as completed has been called.

But I cannot test this in hurl, because when I run the `/run-task` endpoint, I cannot call the `/complete-task/:id` since the `run-task` endpoint blocks.

### Proposal

I don't think this proposal is pretty, but just for inspiration here it is:

```
# Run a task
POST http://localhost/run-task
{
  "name": "task1"
}
FUTURE runtask # The name of the future

# Fetch list of tasks in queue, run the task and call the complete endpoint.
# ...

# Assert the response of the future
FUTURE runtask # Name of the future to assert
HTTP 200
```

**Comment by jcamiel** [comment]
Hi @janwytze 

This kind of scenario is difficult to implement in the current Hurl architecture. As you've seen every entry is a synchronous call (by design). What we've today to deal with this kind of behaviour is [assert-based retried](https://hurl.dev/docs/entry.html#retry).

For instance, if we have an API endpoint to create a task, and an API endpoint to get the status of a task we can do this:

```hurl
# Create task
POST http://localhost/tasks
HTTP 201
[Captures]
name: jsonpath "$.name"

# Pull task status until it is completed
GET http://localhost/tasks/{{name}}
[Options]
retry: 10  # maximum number of retry, -1 for unlimited
HTTP 200
[Asserts]
jsonpath "$.state" == "COMPLETED"
```

Maybe with a mix of shell script and retry, you can find a determinist way of testing your use case. It really seems to me difficult to fit in the current Hurl syntax and architecture.

**Comment by janwytze** [comment]
@jcamiel Thanks for your answer! I already expected that, no problem!
