### ISSUE TITLE
vcruntime140.dll was not found on windows

### ISSUE THREAD

**Issue by faisal-fida** [Orange-OpenSource/hurl#2564]
### What is the current *bug* behavior?

Error box with message: "vcruntime140.dll was not found on windows"

### Steps to reproduce

After intallation on windows, running hurl from commandline

**Comment by lepapareil** [comment]
Hi @faisal-fida, This means that your version of Windows does not include `Microsoft Visual C++`.
To make this work, you need to install the [Microsoft Visual C++ Redistributable Package](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170). Unlike libcurl, libxml2 etc... We do not include vcruntime140.dll in our Windows installer/zip because there are too many associated sub DLL files.

**Comment by faisal-fida** [comment]
Got it, @lepapareil Thanks
