### ISSUE TITLE
Providing files from memory

### ISSUE THREAD

**Issue by nikeee** [Orange-OpenSource/hurl#306]
If I'm getting the docs right, it seems that in requestes referencing files, they would be read from disk (relative to `context_dir` I guess).

Is it possible to provide files to the hurl runner that are read from program memory instead from the disk? This would probably be useful when doing #233.

Maybe something like this?
```rust
enum FileSource {
    Disk { context_dir: str },
    Memory(FileProvider),
}
```

`FileProvider` could be a trait that provides methods to read a file, retrieving the content-length etc.
When it also provides writing abilities, it could be used to capture files from requests in-memory without writing them to disk, possibly adding a CLI option to retain captured files in memory.

Instead of the `FileSource` enum, a plain `FileProvider` could suffice, as one implementing IO access for the `context_dir` could be created on the fly in `fn execute`.

As I'm not that familiar with rust, there might also be an existing trait for this kind of virtual file system.

Looking at the source where the files are included, referencing in-memory data, as it seems that the parameters are passed as classic cURL CLI params:
https://github.com/Orange-OpenSource/hurl/blob/e59e2acc1478c16700bc113bf0932f31df4208a9/packages/hurl/src/http/request_spec.rs#L180-L210

**Comment by nikeee** [comment]
Since #284 is resolved and we'd be able to use Hurl as a library:
Is this something to re-consider?
Hurl really seems like the perfect tool to embed user-defined HTTP requests in an application.
For example, I've got a use case where a user can define how to upload a file. The application could then just invokes the hurl file with some parameters. For performance reasons, we could just provide the file in-memory using some VFS implementation like mentioned above.

**Comment by jcamiel** [comment]
Hi @nikeee you can create a request body that uses memory by building an instance of `HurlFile` instead of parsing a Hurl file.
You have to look at `packages/hurl_core/src/ast/core.rs`: `HurlFile`, `Request`, `Body` struct. Basically, a request has a body field whose value is a `Byte` struct defined like this:

```rust
pub enum Bytes {
    Json(json::Value),
    Xml(String),
    MultilineString(MultilineString),
    OnelineString(Template),
    Base64(Base64),
    File(File),
    Hex(Hex),
}
```

For a memory file, you can use the  `Hex` variant  which can be initialized with a vec of bytes:

```rust
pub struct Hex {
    pub space0: Whitespace,
    pub value: Vec<u8>,
    pub encoded: String,
    pub space1: Whitespace,
}
```

Or use `RawString` variant if you have a text encoded memory buffer.  
It's a bit cumbersome, but it can be done.

For the moment, we're not going to improve this use case.

The core focus of the project is:
- the file format,
- the CLI tool

The aim is to have an excellent CLI tool "à la" curl. The fact that one can use Hurl as a library is a very nice bonus, and we'll try to facilitate it. But our focus is the CLI an not Hurl as a crate. I hope you understand we're trying to stay focused on this features. In any case, I can assist you with sample code to how to forge a request by code, which can be done with the current version (1.8.0).

**Comment by nikeee** [comment]
I'll take a look at that, thank you for this approach. :)

> The core focus of the project is

And that's great! Keep doing awesome stuff!
