### ISSUE TITLE
Add support for all libcurl arguments

### ISSUE THREAD

**Issue by moshloop** [Orange-OpenSource/hurl#378]
This would enable all sorts of modes that are currently not available, especially around authentication and proxying

**Comment by fabricereix** [comment]
Hello, we have the objective to support all curl features but only related to HTTP.

What is your usecase?

**Comment by moshloop** [comment]
I agree that supporting non-http protocols doesn't make sense, out use case is purely HTTP, but we often encounter HTTP services that use all different types of auth, proxy and TLS settings 

NTLM / SPENGO, TLS authentication (on both the server and the proxy), --connect-to,--resolve for hitting individual load balanced backends,  connection/retry settings etc..

**Comment by fabricereix** [comment]
From your last comment, we can implement `--resolve` for the next release (#379)

**Comment by jcamiel** [comment]
Hi @ImportTaste, we're not providing libcurl, the Hurl binary should use your system libcurl and, normally, Hurl can use whatever options the system libcurl is build with.
If you current libcurl has not been build with the right option, I think you can try to rebuild libcurl and then rebuild Hurl.

That's say, could you give us juste more information so we can try to look at it:

- what's your system / version
- how've you installed Hurl
- what's the output of `hurl --version`

**Comment by jcamiel** [comment]
Thanks for the report and effectively I was wrong on Windows, we're embedding a version of libcurl in the Hurl binary so you won't be able to change it easily.

We're going to improve it:

- display the curl features used by hurl when displaying `hurl --version`
- link Hurl with libcurl.dll so one can easily use Hurl with another libcurl version (provided they're compatible) (we're already doing it for libxml etc...)
- provide a libcurl.dll compiled with sensible default (like brotli, HTTPS proxy support etc...)

We've just released a 1.7.0 version and we're trying to address your issue in the next corrective version. If you urgently need it, you can try to build Hurl from sources (it Is not easy on Windows but it's documented on https://github.com/Orange-OpenSource/hurl/tree/master/contrib/windows)

Regards,

**Comment by jcamiel** [comment]
Hi @ImportTaste, we've made some improvement with HTTPS proxy, 
With the last build version (you can get a Windows installer here https://github.com/Orange-OpenSource/hurl/actions/runs/3133999605), we are using the `libcurl` dll instead of embedding `libcurl` as a static library. Could you give it a try (by replacing your own libcurl.dll in the repository) ? 
I don't know how `curl-ca-bundle.crt`is going to behave with this new version, you can test it.
For the moment `hurl --version` doesn't display if HTTPS proxy is supported or not but we're working on it (thanks @lepapareil who is doing all the works for Windows support)

**Comment by jcamiel** [comment]
I'm closing this issue for the moment, fill free to open new issue for a specific curl option that you would like to be supported with Hurl.
