### ISSUE TITLE
JSON path regex support

### ISSUE THREAD

**Issue by bondz** [Orange-OpenSource/hurl#735]
Given that an api responds with

```json
{
	"url": [
		"https://www.youtube.com/watch?v=dQw4w9WgXcQ",
		"https://www.youtube.com/watch?v=dQw4w9WgXcQ",
		"https://www.youtube.com/watch?v=dQw4w9WgXcQ",
		"https://www.youtube.com/watch?v=dQw4w9WgXcQ",
		"https://www.youtube.com/watch?v=dQw4w9WgXcQ",
		"https://www.youtube.com/watch?v=dQw4w9WgXcQ",
		"https://www.youtube.com/watch?v=dQw4w9WgXcQ"
	]
}
```

I then write a hurl Assert to check that all urls begin with `https`

```hurl
jsonpath "$.url[?(/^(?!https:)/.test(@))]" not exists
```

This fails with the error that the `jsonpath` is not valid. I've tested this with an online evaluator like https://jsonpath.com/ and its valid.

Is it possible to support filter expressions with regex in hurl or is there a different way to write this assertion?

**Comment by jcamiel** [comment]
Hi @bondz, 

Unfortunately, currently there is no easy way to do your assertions with Hurl. We've implemented <https://goessner.net/articles/JsonPath/> (that's why you've a different result with  <https://jsonpath.com/>).

That's said, your issue is related to #347 which is proposing to add an easy way to assert every item of the collection. We would be able to write:

```
GET https://example.net/api
HTTP*/* 200
[Asserts]
jsonpath "$.url" each startsWith "https://"
```
(The novelty being the keyword `each`, `any` and `none`).

As it's a simple way to address a lot of issues like your, we'll certainly support "soon".

For the moment, you can still hardcode your assertions. It's not easy but it can do the job if you know the size of the returned array.

```
GET https://example.net/api
HTTP*/* 200
[Asserts]
jsonpath "$.url[0]" startsWith "https://"
jsonpath "$.url[1]" startsWith "https://"
jsonpath "$.url[2]" startsWith "https://"
jsonpath "$.url[3]" startsWith "https://"
...
```

**Comment by bondz** [comment]
Thank you for the quick response @jcamiel

Looks like this would be resolved by the new syntax when it's implemented. 

I'll close this for now, thanks again.
