### ISSUE TITLE
cannot use variables in [BasicAuth]

### ISSUE THREAD

**Issue by andres-lowrie** [Orange-OpenSource/hurl#898]
Hello, great tool!

Not sure if this is a bug or just a misunderstanding but I'm trying to use variables in the `[BasicAuth]` section and it looks like the tool doesn't like it:

<sub>test.hurl</sub>
```
POST http://localhost
[BasicAuth]
{{user}}:{{pass}}
```

and then I call it like 
```
hurl --variable user=bob --variable pass=secret test.hurl
```

and get back
```
error: Parsing JSON
  --> passforbasicauth.hurl:2:2
   |
 2 | [BasicAuth]
   |  ^ JSON error
   |
```

Is that _supposed_ to work? 

----

My use case is one where I want to be able to define the secrets in another file and not in the hurl file itself to make it easy to share it

**Comment by jcamiel** [comment]
Hi, 

Unfortunately, you can't use this syntax for now.

If you want to not expose credentials in the Hurl file, you can do the following

1. use [an Authorization header](https://hurl.dev/docs/samples.html#basic-authentication)

```
POST http://localhost
Authorization: Basic {{digest}}
```

Where the variable `digest` have been computed like that:
```
$ hurl --variable digest=`echo -n 'bob:secret' | base64` test.hurl
```

Or you can also make a environment variable like this:

```
$ export HURL_digest=`echo -n 'bob:secret' | base64`
$ hurl test.hurl
```

In this case, any `HURL_foo` environment variable is injected as `foo`variable in the Hurl file.

2. use [`--user`](https://hurl.dev/docs/manual.html#user) option but you will add a basic authentication header to all your requests.

We can think about how to improve things for basic authentication, because in most cases you don't want to write your credentials in a file,

**Comment by andres-lowrie** [comment]
fair enough. Thanks for looking into this!

**Comment by tpluscode** [comment]
I just tried the same and would also ask for variables to work in `[BasicAuth]`.

My reasoning is that having credentials in a `.env` file in dev env and secrets in CI makes it easier to run hurl in both cases. Otherwise, the necessity to pass credentials from CLI is a little troublesome

**Comment by jcamiel** [comment]
Hi @tpluscode, @andres-lowrie, 

This issue is now merged on master.
You can now write:

```hurl
POST http://foo.com/login
[BasicAuth]
{{user}}: {{password}}
HTTP 200
```
